universe = vanilla
Executable = /afs/cern.ch/user/c/chiw/condor/preCut-mu-condor/run_job.sh
arguments = $(DATA_DIR)
Transfer_Input_Files = /afs/cern.ch/user/c/chiw/condor/preCut-mu-condor/runReadTreeX.C.tpl, \
                       /afs/cern.ch/user/c/chiw/condor/preCut-mu-condor/ReadTree.C
Transfer_Output_Files = filtered_data_preCut.root
Output_Destination = root://eosuser.cern.ch/$(DATA_DIR)

WhenToTransferOutput = ON_EXIT  

Output = /afs/cern.ch/user/c/chiw/condor/preCut-mu-condor/logs/$(Cluster)_$(Process).stdout
Error = /afs/cern.ch/user/c/chiw/condor/preCut-mu-condor/logs/$(Cluster)_$(Process).stderr
Log = /afs/cern.ch/user/c/chiw/condor/preCut-mu-condor/logs/$(Cluster)_$(Process).log

request_memory = 8GB
request_cpus = 1
queue DATA_DIR from /afs/cern.ch/user/c/chiw/condor/preCut-mu-condor/datadir.list